AWSTemplateFormatVersion : 2010-09-09
Parameters:
  BucketName:
    Type: String
    Default: 'siva-lambda-1'
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  JavaRepoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: siva-lambda-1
        S3Key: JavaRepoLambda.zip
      FunctionName: JavaRepo
      Handler: sample.Handler
      MemorySize: 128
      Runtime: java11
      Role: !GetAtt ProcessingLambdaExecutionRole.Arn


  ProcessingLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allowLogging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: getAndDeleteObjects
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:  !Sub 'arn:aws:s3:::${BucketName}/*'